version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "7777:7777"
    volumes:
      - ./data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge