version: '3.8'

services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - BASE_URL=${BASE_URL:-http://localhost:80}
    restart: unless-stopped